id = "WebSmithing"
name = "Web_Smithing"
description = "A mod that adds mining and smithing functionality to the fish frenzy!"
version = "0.1"
homepage = "https://github.com/Seltraeh/WebSmithing"
author = "Esphee"

icon = "./thunderstore/icon.png"
readme = "./thunderstore/README.md"
changelog = "./thunderstore/CHANGELOG.md"

[project]
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"
